{
 "title": "User Service",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "user_service_db_pool_total_conns",
     "legendFormat": "__auto"
    },
    {
     "expr": "user_service_db_pool_idle_conns",
     "legendFormat": "__auto"
    },
    {
     "expr": "user_service_db_pool_acquired_conns",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Query P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum(rate(user_service_db_query_duration_seconds_bucket[1m])) by (le,\n  operation))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(user_service_http_requests_total[1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(rate(user_service_http_request_duration_seconds_bucket[1m])) by (le,\n  route))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}